/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Sindicalizado;
import Controller.Util;
import DAO.Dados_Sindicalizado_Pessoais_DAO;
import DAO.Sindicalizado_DAO;
import Model.Dados_Rurais;
import Model.Dados_Pessoais;
import java.awt.Dimension;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import org.apache.bcel.generic.AALOAD;

/**
 *
 * @author helde
 */
public class Cadastrar_Sindi extends javax.swing.JInternalFrame {

    Dados_Pessoais dadosp = new Dados_Pessoais();
    Dados_Rurais pr;
    Sindicalizado si = new Sindicalizado();
    Dados_Sindicalizado_Pessoais_DAO DADOSP = new Dados_Sindicalizado_Pessoais_DAO();

    DateFormat df = DateFormat.getDateInstance();

    public String status = "";
    int id = 0, idade, erro = 0, totalFazenda = 0, q = 0, ID_TABELA = 0;
    boolean alterar = false, cont = false, validacao = false;

    ArrayList<Dados_Rurais> RURAL = new ArrayList<>();

    public Cadastrar_Sindi() {
        initComponents();

        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastrar_Sindi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Cadastrar_Sindi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Cadastrar_Sindi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Cadastrar_Sindi.class.getName()).log(Level.SEVERE, null, ex);
        }

        validaNumerosLetras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        FORM_GUIAS = new javax.swing.JTabbedPane();
        PESQUISAR_SIND = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DADOS_PESSOAIS_SIND = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        NOME = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        ESTADOCIVI = new javax.swing.JComboBox<>();
        jLabel90 = new javax.swing.JLabel();
        CELULAR = new javax.swing.JFormattedTextField();
        jLabel92 = new javax.swing.JLabel();
        NASCIONALIDADE = new javax.swing.JTextField();
        jLabel91 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        CPF = new javax.swing.JFormattedTextField();
        jLabel80 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        RG = new javax.swing.JFormattedTextField();
        jLabel82 = new javax.swing.JLabel();
        RESERVISTA = new javax.swing.JFormattedTextField();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        CATEGORIA = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        TITULO_ELEITO = new javax.swing.JFormattedTextField();
        jLabel94 = new javax.swing.JLabel();
        ZONA = new javax.swing.JFormattedTextField();
        jLabel95 = new javax.swing.JLabel();
        SECAO = new javax.swing.JFormattedTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        PAI = new javax.swing.JTextField();
        MAE = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        BOTAO_ALTERAR_ = new javax.swing.JLabel();
        TOTAO_REFAZER = new javax.swing.JLabel();
        BOTAO_AVANCAR_ = new javax.swing.JLabel();
        CANCELAR = new javax.swing.JLabel();
        DATAEXPE = new com.toedter.calendar.JDateChooser();
        NASCIMENTO = new com.toedter.calendar.JDateChooser();
        DADOS_RURAIS_SIND = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABELA_PROPRIEDADE_RURAL = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        TOTAL_FAZ = new javax.swing.JTextField();
        BOTAO_CADASTRAR_ = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        NOMEFAZENDA = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        TEMPOCOMPRA = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        CODINCRA = new javax.swing.JFormattedTextField();
        jLabel60 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OUTRASATIVI = new javax.swing.JTextPane();
        jLabel64 = new javax.swing.JLabel();
        BOTAO_VOLTAR_ = new javax.swing.JLabel();
        BOTAO_REFAZER_ = new javax.swing.JLabel();
        BOTAO_SALVAR_ = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        RESIDEN_ATUAL = new javax.swing.JTextField();
        LOGRADOURO = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        AREAFAZENDA = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        Numero_NIRF = new javax.swing.JFormattedTextField();
        MUNICEDE = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jLabel1.setText("jLabel1");

        setClosable(true);
        setIconifiable(true);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar.png"))); // NOI18N
        jLabel4.setText("DADOS RURAIS");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fazenda.png"))); // NOI18N

        javax.swing.GroupLayout PESQUISAR_SINDLayout = new javax.swing.GroupLayout(PESQUISAR_SIND);
        PESQUISAR_SIND.setLayout(PESQUISAR_SINDLayout);
        PESQUISAR_SINDLayout.setHorizontalGroup(
            PESQUISAR_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PESQUISAR_SINDLayout.createSequentialGroup()
                .addContainerGap(1141, Short.MAX_VALUE)
                .addGroup(PESQUISAR_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESQUISAR_SINDLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESQUISAR_SINDLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37))))
        );
        PESQUISAR_SINDLayout.setVerticalGroup(
            PESQUISAR_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PESQUISAR_SINDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(22, 22, 22))
        );

        FORM_GUIAS.addTab("PESQUISAR  SINDICALIZADO", PESQUISAR_SIND);

        jLabel75.setText("Nome:");

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 0, 0));
        jLabel76.setText("*");

        jLabel77.setText("Data de nascimento:");

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 0, 0));
        jLabel78.setText("*");

        jLabel81.setText("Estado civil:");

        ESTADOCIVI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Casado", "Solteiro", "Viúvo", "Divorciado", " " }));

        jLabel90.setText("Celular:");

        try {
            CELULAR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9#### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CELULAR.setToolTipText("");
        CELULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CELULARActionPerformed(evt);
            }
        });

        jLabel92.setText("Nascionalidade:");

        NASCIONALIDADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NASCIONALIDADEActionPerformed(evt);
            }
        });

        jLabel91.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(255, 0, 0));
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel91.setText("*");
        jLabel91.setIconTextGap(8);

        jLabel89.setText("Data de expedição:");

        jLabel98.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 0, 0));
        jLabel98.setText("*");

        try {
            CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.### - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel80.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 0, 0));
        jLabel80.setText("*");

        jLabel83.setText("RG:");

        try {
            RG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        RG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGActionPerformed(evt);
            }
        });

        jLabel82.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 0, 0));
        jLabel82.setText("*");
        jLabel82.setPreferredSize(new java.awt.Dimension(13, 30));

        try {
            RESERVISTA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel96.setText("Reservista:");

        jLabel97.setText("Categoria:");

        jLabel93.setText("Titulo de eleitor:");

        try {
            TITULO_ELEITO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel94.setText("Zona:");

        try {
            ZONA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel95.setText("Seção:");

        try {
            SECAO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        SECAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SECAOActionPerformed(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel84.setText("Pai:");

        PAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PAIMouseEntered(evt);
            }
        });

        MAE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MAEMouseEntered(evt);
            }
        });

        jLabel85.setText("Mãe:");

        jLabel86.setText("FILIAÇÃO:");

        jLabel87.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 0, 0));
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel87.setText("*");
        jLabel87.setIconTextGap(8);
        jLabel87.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel88.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 0, 0));
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel88.setText("*");
        jLabel88.setIconTextGap(8);
        jLabel88.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel86)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel84)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PAI, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel87)
                .addGap(26, 26, 26)
                .addComponent(jLabel85)
                .addGap(4, 4, 4)
                .addComponent(MAE, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel88)
                .addGap(4, 4, 4))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel88)
                    .addComponent(jLabel87)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel84)
                        .addComponent(jLabel85)
                        .addComponent(MAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel86)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel79.setText("CPF:");

        BOTAO_ALTERAR_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar_1.png"))); // NOI18N

        TOTAO_REFAZER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizaz.png"))); // NOI18N
        TOTAO_REFAZER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TOTAO_REFAZERMouseClicked(evt);
            }
        });

        BOTAO_AVANCAR_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/proximo.png"))); // NOI18N
        BOTAO_AVANCAR_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTAO_AVANCAR_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BOTAO_AVANCAR_MouseEntered(evt);
            }
        });

        CANCELAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        CANCELAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CANCELARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DADOS_PESSOAIS_SINDLayout = new javax.swing.GroupLayout(DADOS_PESSOAIS_SIND);
        DADOS_PESSOAIS_SIND.setLayout(DADOS_PESSOAIS_SINDLayout);
        DADOS_PESSOAIS_SINDLayout.setHorizontalGroup(
            DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                        .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                                .addComponent(jLabel92)
                                .addGap(6, 6, 6)
                                .addComponent(NASCIONALIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel91))
                            .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                                .addComponent(jLabel96)
                                .addGap(3, 3, 3)
                                .addComponent(RESERVISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                                .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                                        .addComponent(jLabel79)
                                        .addGap(6, 6, 6)
                                        .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel80)
                                        .addGap(107, 107, 107)
                                        .addComponent(jLabel83)
                                        .addGap(4, 4, 4)
                                        .addComponent(RG, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(jLabel89)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                                        .addComponent(TOTAO_REFAZER, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)))
                                .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BOTAO_ALTERAR_)
                                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(DATAEXPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel98))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                                .addComponent(jLabel97)
                                .addGap(9, 9, 9)
                                .addComponent(CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel93)
                                .addGap(4, 4, 4)
                                .addComponent(TITULO_ELEITO, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel94)
                                .addGap(4, 4, 4)
                                .addComponent(ZONA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel95)
                                .addGap(6, 6, 6)
                                .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BOTAO_AVANCAR_)
                                    .addComponent(SECAO, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                        .addComponent(jLabel75)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NOME, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel76)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel77)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NASCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel78)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel81)
                        .addGap(3, 3, 3)
                        .addComponent(ESTADOCIVI, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel90)
                        .addGap(12, 12, 12)
                        .addComponent(CELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DADOS_PESSOAIS_SINDLayout.setVerticalGroup(
            DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                .addComponent(CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel76)
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel81))
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel75)
                            .addComponent(NOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ESTADOCIVI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel90))
                    .addComponent(CELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel77))
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NASCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel78))))
                .addGap(45, 45, 45)
                .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                            .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel79)))
                            .addGap(11, 11, 11))
                        .addComponent(jLabel80, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel92)
                    .addComponent(NASCIONALIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel83))
                                .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel89))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DATAEXPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel98))
                            .addGap(2, 2, 2))))
                .addGap(57, 57, 57)
                .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RESERVISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel97)
                    .addComponent(CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TITULO_ELEITO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZONA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SECAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DADOS_PESSOAIS_SINDLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel96)
                            .addComponent(jLabel93)
                            .addComponent(jLabel94)
                            .addComponent(jLabel95))))
                .addGap(43, 43, 43)
                .addGroup(DADOS_PESSOAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TOTAO_REFAZER, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTAO_AVANCAR_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BOTAO_ALTERAR_, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        FORM_GUIAS.addTab("DADOS PESSOAIS", DADOS_PESSOAIS_SIND);

        jLabel2.setText("SELECIONE A PROPRIEDADE RURAL");

        TABELA_PROPRIEDADE_RURAL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de identificação (ID)", "Nome da propriedade", "Área da propriedade", "Município cede", "Tempo de compra da propriedade", "Logradouro", "Número do Imóvel no NIRF", "Número do imóvel no INCRA", "Residência atual", "Outras atividades"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TABELA_PROPRIEDADE_RURAL);

        jLabel10.setText("QUANTIDADE DE PROPRIEDADES RURAIS QUE SERÃO CADASTRADAS:");

        TOTAL_FAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTAL_FAZActionPerformed(evt);
            }
        });

        BOTAO_CADASTRAR_.setText("Iniciar Cadastro");
        BOTAO_CADASTRAR_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_CADASTRAR_ActionPerformed(evt);
            }
        });

        jLabel45.setText("Nome da propriedade rural:");

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 0, 0));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel67.setText("*");
        jLabel67.setIconTextGap(8);
        jLabel67.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel63.setText("Tempo de compra da propriedade:");

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 0, 0));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel71.setText("*");
        jLabel71.setIconTextGap(8);
        jLabel71.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        try {
            CODINCRA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CODINCRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODINCRAActionPerformed(evt);
            }
        });

        jLabel60.setText("Código do imovel no INCRA:");

        jScrollPane3.setViewportView(OUTRASATIVI);

        jLabel64.setText("Outras atividades:");

        BOTAO_VOLTAR_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        BOTAO_VOLTAR_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTAO_VOLTAR_MouseClicked(evt);
            }
        });

        BOTAO_REFAZER_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizaz.png"))); // NOI18N
        BOTAO_REFAZER_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTAO_REFAZER_MouseClicked(evt);
            }
        });

        BOTAO_SALVAR_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar_1.png"))); // NOI18N
        BOTAO_SALVAR_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTAO_SALVAR_MouseClicked(evt);
            }
        });

        jLabel74.setText("Residência atual:");

        jLabel46.setText("Logradouro:");

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 0, 0));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel68.setText("*");
        jLabel68.setIconTextGap(8);
        jLabel68.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel62.setText("Area da prorpiedade:");

        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 0, 0));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel70.setText("*");
        jLabel70.setIconTextGap(8);
        jLabel70.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel61.setText("Numero NIRF:");

        try {
            Numero_NIRF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel59.setText("Municipio cede:");

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 0, 0));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel69.setText("*");
        jLabel69.setIconTextGap(8);
        jLabel69.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel64)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(BOTAO_VOLTAR_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BOTAO_REFAZER_, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BOTAO_SALVAR_, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addGap(4, 4, 4)
                                        .addComponent(NOMEFAZENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel67))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel60)
                                        .addGap(4, 4, 4)
                                        .addComponent(CODINCRA, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel63)
                                        .addGap(1, 1, 1)
                                        .addComponent(TEMPOCOMPRA, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel71)))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel62)
                                                .addGap(3, 3, 3)
                                                .addComponent(AREAFAZENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel70))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel46)
                                                .addGap(4, 4, 4)
                                                .addComponent(LOGRADOURO, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel68)))
                                        .addGap(82, 82, 82)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel61)
                                                .addGap(4, 4, 4)
                                                .addComponent(Numero_NIRF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel59)
                                                .addGap(3, 3, 3)
                                                .addComponent(MUNICEDE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel69))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel74)
                                        .addGap(4, 4, 4)
                                        .addComponent(RESIDEN_ATUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TOTAL_FAZ, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BOTAO_CADASTRAR_)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(TOTAL_FAZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTAO_CADASTRAR_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NOMEFAZENDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel45))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AREAFAZENDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel62))
                            .addComponent(jLabel70)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MUNICEDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel59))
                            .addComponent(jLabel69))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LOGRADOURO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel46))
                            .addComponent(jLabel68)
                            .addComponent(jLabel71)
                            .addComponent(TEMPOCOMPRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel63)
                            .addComponent(Numero_NIRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel61)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CODINCRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel60)
                                    .addComponent(RESIDEN_ATUAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel74))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel64))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BOTAO_VOLTAR_, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BOTAO_REFAZER_, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BOTAO_SALVAR_, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout DADOS_RURAIS_SINDLayout = new javax.swing.GroupLayout(DADOS_RURAIS_SIND);
        DADOS_RURAIS_SIND.setLayout(DADOS_RURAIS_SINDLayout);
        DADOS_RURAIS_SINDLayout.setHorizontalGroup(
            DADOS_RURAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DADOS_RURAIS_SINDLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DADOS_RURAIS_SINDLayout.setVerticalGroup(
            DADOS_RURAIS_SINDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DADOS_RURAIS_SINDLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        FORM_GUIAS.addTab("DADOS RURAIS", DADOS_RURAIS_SIND);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FORM_GUIAS, javax.swing.GroupLayout.PREFERRED_SIZE, 1301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FORM_GUIAS, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CODINCRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODINCRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CODINCRAActionPerformed

    private void BOTAO_AVANCAR_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTAO_AVANCAR_MouseEntered
        BOTAO_AVANCAR_.setToolTipText("AVANÇAR");
    }//GEN-LAST:event_BOTAO_AVANCAR_MouseEntered

    private void MAEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAEMouseEntered
        MAE.setToolTipText("Filiação");
    }//GEN-LAST:event_MAEMouseEntered

    private void PAIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAIMouseEntered
        PAI.setToolTipText("Filiação");
    }//GEN-LAST:event_PAIMouseEntered

    private void SECAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SECAOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SECAOActionPerformed

    private void RGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGActionPerformed
        DATAEXPE.setEnabled(true);
    }//GEN-LAST:event_RGActionPerformed

    private void NASCIONALIDADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NASCIONALIDADEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NASCIONALIDADEActionPerformed

    private void CELULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CELULARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CELULARActionPerformed

    private void BOTAO_CADASTRAR_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_CADASTRAR_ActionPerformed
        if ("".equals(TOTAL_FAZ.getText())) {
            JOptionPane.showMessageDialog(null, "Infome o total de propriedades rurais que deseja cadastrar", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            TOTAL_FAZ.requestFocus();
            bloquear_campus_rurais();
        } else {
            int t = Integer.parseInt(TOTAL_FAZ.getText());
            if (t == 0) {
                JOptionPane.showMessageDialog(null, "Infome o total de propriedades rurais que deseja cadastrar e que seja maior que 0", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
                TOTAL_FAZ.setText("");
                TOTAL_FAZ.requestFocus();
            } else {
                totalFazenda = t;
                desbloquear_campus_rurais();
            }
        }
    }//GEN-LAST:event_BOTAO_CADASTRAR_ActionPerformed

    private void TOTAO_REFAZERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TOTAO_REFAZERMouseClicked
        limparCampus_Pessoais();
    }//GEN-LAST:event_TOTAO_REFAZERMouseClicked

    private void BOTAO_AVANCAR_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTAO_AVANCAR_MouseClicked
        if (erro == 1) {
            erro = 0;
        }
        validacao = validar_obrigatorios_pessoais();
        if (validacao) {
            preencher_objeto_Pessoal();
            selecionar_guia(2);
            bloquear_campus_rurais();
        }
    }//GEN-LAST:event_BOTAO_AVANCAR_MouseClicked

    private void TOTAL_FAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTAL_FAZActionPerformed
        limparCampus_Rurais();
        bloquear_campus_rurais();
    }//GEN-LAST:event_TOTAL_FAZActionPerformed

    private void BOTAO_VOLTAR_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTAO_VOLTAR_MouseClicked
        selecionar_guia(1);
    }//GEN-LAST:event_BOTAO_VOLTAR_MouseClicked

    private void CANCELARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELARMouseClicked
        limparCampus_Pessoais();
        selecionar_guia(0);
    }//GEN-LAST:event_CANCELARMouseClicked

    private void BOTAO_REFAZER_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTAO_REFAZER_MouseClicked
        limparCampus_Rurais();
    }//GEN-LAST:event_BOTAO_REFAZER_MouseClicked

    private void BOTAO_SALVAR_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTAO_SALVAR_MouseClicked

        validacao = validar_obrigatorios_rurais();
        if (validacao) {
            if (totalFazenda > 1) {
                if (q <= totalFazenda) {
                    if ("cadastrar sind".equals(status)) { //cadastrar um novo sindicalizado completo                                             
                        RURAL.add(preencher_objeto_Rural());
                        LISTAR_TABELA(RURAL);
                        limparCampus_Rurais();
                        q++;
                        int a = totalFazenda - 1;
                        if (q <= a) {
                            JOptionPane.showMessageDialog(null, "Informe os dados das outras propriedades ruraris que deseja cadastrar", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                            NOMEFAZENDA.requestFocus();
                        } else {
                            // AQUI EU TENHO Q MANDA SALVA OS DOIS OBJETOS (PESSOAL E RURAL) SE CASO FOR CADASTRAR MAIS DE UMA PROPRIEDADE RURAL
                            // os 2 objetos ja estão preenchidos, entao tenho que manda eles pra salva assim: (se, pr), e é um novo cadastro completo de sindicalizado

                            id = DADOSP.salvar_Dados_P(dadosp);
                            DADOSP.salvar_Dados_R(RURAL, id);

                            limparCampus_Rurais();
                            limparTabela(totalFazenda);
                            TOTAL_FAZ.setText("");
                            limparCampus_Pessoais();
                            selecionar_guia(1);
                        }
                    } else if ("".equals(status)) {
                        // alteração de dados: adicionar novas propriedades rurais a um sindicalizado que ja é cadastrado
                        validacao = validar_obrigatorios_rurais();
                        if (validacao) {
                            preencher_objeto_Rural();
                        }
                    }
                }
            } else if (totalFazenda == 1) {
                validacao = validar_obrigatorios_rurais();
                if (validacao) {
                    preencher_objeto_Rural();
                    // AQUI EU TENHO Q MANDA SALVA OS DOIS OBJETOS (PESSOAL E RURAL) SE CASO FOR CADASTRAR SÓ UMA PROPRIEDADE RURAL
                    // os 2 objetos ja estão preenchidos, entao tenho que manda eles pra salva assim: (se, pr)
                    q++;
                }
            } else if ("".equals(TOTAL_FAZ.getText())) { // alterar os dados rurais, então não sera informado o total de propriedades para ser cadastradas 
                if ("altera propri".equals(status)) {
                    validacao = validar_obrigatorios_rurais();
                    if (validacao) {

                    }
                }
            }
        }

    }//GEN-LAST:event_BOTAO_SALVAR_MouseClicked

    public void selecionar_guia(int n) {
        this.FORM_GUIAS.setEnabledAt(n, true); // desabilita toda a aba 1
        this.FORM_GUIAS.setSelectedIndex(n);
        switch (n) {
            case 0:
                this.FORM_GUIAS.setEnabledAt(1, false); // desabilita toda a aba 1
                this.FORM_GUIAS.setEnabledAt(2, false); // desabilita toda a aba 2
                break;
            case 1:
                this.FORM_GUIAS.setEnabledAt(0, false); // desabilita toda a aba 0
                this.FORM_GUIAS.setEnabledAt(2, false); // desabilita toda a aba 2
                if ("cadastrar sind".equals(status)) {
                    BOTAO_ALTERAR_.setVisible(false);
                    CANCELAR.setVisible(false);
                }
                break;
            case 2:
                this.FORM_GUIAS.setEnabledAt(0, false); // desabilita toda a aba 0
                this.FORM_GUIAS.setEnabledAt(1, false); // desabilita toda a aba 1
                break;
            default:
                break;
        }
    }

    public void setPosicao() { // faz o formulario aparecer centralizado na tela
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void bloquear_campus_rurais() {
        NOMEFAZENDA.setEnabled(false);
        AREAFAZENDA.setEnabled(false);
        LOGRADOURO.setEnabled(false);
        Numero_NIRF.setEnabled(false);
        MUNICEDE.setEnabled(false);
        TEMPOCOMPRA.setEnabled(false);
        CODINCRA.setEnabled(false);
        OUTRASATIVI.setEnabled(false);
        RESIDEN_ATUAL.setEnabled(false);

    }

    public void desbloquear_campus_rurais() {
        NOMEFAZENDA.setEnabled(true);
        AREAFAZENDA.setEnabled(true);
        LOGRADOURO.setEnabled(true);
        Numero_NIRF.setEnabled(true);
        MUNICEDE.setEnabled(true);
        TEMPOCOMPRA.setEnabled(true);
        CODINCRA.setEnabled(true);
        OUTRASATIVI.setEnabled(true);
        RESIDEN_ATUAL.setEnabled(true);
    }

    public void limparCampus_Pessoais() {
        NOME.setText("");
        NASCIMENTO.setDate(null);
        ESTADOCIVI.setSelectedIndex(0);
        CPF.setValue("");
        CELULAR.setValue("");
        RG.setValue("");
        DATAEXPE.setDate(null);
        NASCIONALIDADE.setText("");
        RESERVISTA.setValue("");
        CATEGORIA.setText("");
        TITULO_ELEITO.setValue("");
        ZONA.setValue("");
        SECAO.setValue("");
        PAI.setText("");
        MAE.setText("");
    }

    public void limparCampus_Rurais() {
        NOMEFAZENDA.setText("");
        AREAFAZENDA.setText("");
        LOGRADOURO.setText("");
        ;
        Numero_NIRF.setValue("");
        MUNICEDE.setText("");
        TEMPOCOMPRA.setText("");
        CODINCRA.setValue("");
        OUTRASATIVI.setText("");
        RESIDEN_ATUAL.setText("");
    }

    public void preencher_campus_pessoais(Dados_Pessoais si) {
        NOME.setText(si.getNome());
        NASCIMENTO.setDate(si.getDataNasci());
        ESTADOCIVI.setSelectedItem(si.getEstadoCivil());
        CPF.setText(si.getCpf());
        CELULAR.setText(si.getCelular());
        RG.setText(si.getRg());
        DATAEXPE.setDate(si.getDataExpedicao());
        NASCIONALIDADE.setText(si.getNascionalidade());
        RESERVISTA.setText(si.getReservista());
        CATEGORIA.setText(si.getCategoria());
        TITULO_ELEITO.setText(si.getTituloEleito());
        if (si.getZona() == 0) {
            ZONA.setText("");
        } else {
            ZONA.setText(String.valueOf(si.getZona()));
        }
        if (si.getSecao() == 0) {
            SECAO.setText("");
        } else {
            SECAO.setText(String.valueOf(si.getSecao()));
        }
        PAI.setText(si.getPai());
        MAE.setText(si.getMae());

        status = "alterar";
        this.id = si.getId();
        CANCELAR.setVisible(true);
        TOTAO_REFAZER.setVisible(false);
        BOTAO_ALTERAR_.setVisible(false);
    }

    public void preencher_campus_rurais(Dados_Rurais pr) {
        NOMEFAZENDA.setText(pr.getNomeFazenda());
        AREAFAZENDA.setText(pr.getAreaPropri());
        LOGRADOURO.setText(pr.getLogradouro());
        Numero_NIRF.setText(pr.getNIRF());
        MUNICEDE.setText(pr.getMuniciSede());
        TEMPOCOMPRA.setText(pr.getTempoCompra());
        CODINCRA.setText(pr.getCodINCRA());
        OUTRASATIVI.setText(pr.getOutrasA());
        RESIDEN_ATUAL.setText(pr.getResidenciaAtual());

        status = "alterar";
        this.id = pr.getId();
    }

    public final void validaNumerosLetras() {
        Util.soLetras(NOME);
        Util.soLetras(CATEGORIA);
        Util.soNumeros(RG);
        Util.soLetras(NASCIONALIDADE);
        Util.soNumeros(RESERVISTA);
        Util.soNumeros(TITULO_ELEITO);
        Util.soNumeros(ZONA);
        Util.soNumeros(SECAO);
        Util.soLetras(PAI);
        Util.soLetras(MAE);
        Util.soLetras(MUNICEDE);
        Util.soLetras(RESIDEN_ATUAL);
    }

    public boolean validar_obrigatorios_pessoais() {
        String cpf;

        if ("".equals(NOME.getText())) {
            JOptionPane.showMessageDialog(null, "Informe o nome");
            erro = 1;
            NOME.requestFocus();
        } else if (NASCIMENTO.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Informe a data de nascimento");
            erro = 1;
            NASCIMENTO.requestFocus();
        } else {
            String data = Util.verificar_Data(df.format(NASCIMENTO.getDate()), true);
            idade = Util.idade;

            if ("//".equals(data)) {
                if (idade < 18) {
                    JOptionPane.showMessageDialog(null, "Não é permitido o cadastramento de sindicalizado menor de idade", "Atenção", JOptionPane.ERROR_MESSAGE);
                    erro = 1;
                } else {
                    JOptionPane.showMessageDialog(null, "A data de nascimento do sindicalizado é invalida", "Atenção", JOptionPane.ERROR_MESSAGE);
                    erro = 1;
                }
                NASCIMENTO.setDate(null);
            }
        }
        if (erro == 0 && "   .   .    -   ".equals(CPF.getText()) || "".equals(CPF.getText())) {
            erro = 1;
            JOptionPane.showMessageDialog(null, "Informe o CPF do sindicalizado ");
            CPF.requestFocus();
        } else {
            cpf = si.validar_CPF(CPF.getText());
            if ("".equals(cpf) && erro == 0) {
                erro = 1;
                JOptionPane.showMessageDialog(null, "O CPF do sindicalizado é invalido", "Atenção CPF invalido", JOptionPane.ERROR_MESSAGE);
                CPF.setText("   .   .    -   ");
                CPF.requestFocus();
            } else {
                String i;
                if (alterar) {
                    i = si.verificar_CPF(CPF.getText(), id);
                } else {
                    i = si.verificar_CPF(CPF.getText(), 0);
                }
                if ("tem dono".equals(i)) {
                    erro = 1;
                    JOptionPane.showMessageDialog(null, "O CPF informado já esta cadastrado", "Atenção CPF invalido", JOptionPane.ERROR_MESSAGE);
                    CPF.setText("");
                    CPF.requestFocus();
                }
            }
        }

        if ((erro == 0) && "       ".equals(RG.getText()) || "".equals(RG.getText())) {
            JOptionPane.showMessageDialog(null, "Informe o RG");
            RG.requestFocus();
            erro = 1;
        } else {
            String R_G = si.validadar_RG(RG.getText());
            if ("".equals(R_G) && erro == 0) {
                erro = 1;
                JOptionPane.showMessageDialog(null, "O RG do sindicalizado é invalido", "Atenção RG invalido", JOptionPane.ERROR_MESSAGE);
                RG.setText("       ");
                RG.requestFocus();
            } else {
                String i;
                if (alterar) {
                    i = si.verificar_RG(RG.getText(), id);
                } else {
                    i = si.verificar_RG(RG.getText(), 0);
                }
                if ("tem dono".equals(i)) {
                    erro = 1;
                    JOptionPane.showMessageDialog(null, "O RG informado já esta cadastrado", "Atenção RG invalido", JOptionPane.ERROR_MESSAGE);
                    RG.setText("");
                    RG.requestFocus();
                }
            }
        }
        if (DATAEXPE.getDate() == null && erro == 0) {
            JOptionPane.showMessageDialog(null, "Informe a data de expedição do RG");
            DATAEXPE.requestFocus();
            erro = 1;
        } else if (erro == 0) {
            String data = Util.verificar_Data(df.format(DATAEXPE.getDate()), false);
            if ("//".equals(data)) {
                JOptionPane.showMessageDialog(null, "A data de Expedição do RG do sindicalizado é invalida", "Atenção", JOptionPane.ERROR_MESSAGE);
                erro = 1;
                DATAEXPE.setDate(null);
                DATAEXPE.requestFocus();
            }
        }
        if ("".equals(NASCIONALIDADE.getText()) && erro == 0) {
            JOptionPane.showMessageDialog(null, "Informe a nascionalidade");
            NASCIONALIDADE.requestFocus();
            erro = 1;
        } else if ("".equals(PAI.getText()) && erro == 0) {
            JOptionPane.showMessageDialog(null, "Informe a filiação paterna");
            PAI.requestFocus();
            erro = 1;
        } else if ("".equals(MAE.getText()) && erro == 0) {
            JOptionPane.showMessageDialog(null, "Informe a filiação materna");
            MAE.requestFocus();
            erro = 1;
        } else if (!"(  ) 9     -     ".equals(CELULAR.getText()) && erro == 0) {        // DAQUI PRA BAIXO COMEÇA A VALIDAÇÃO DOS QUE NÃO SÃO OBRIGATÓRIOS 
            String TEL = si.validadar_Telefone(CELULAR.getText());
            if ("".equals(TEL)) {
                erro = 1;
                JOptionPane.showMessageDialog(null, "O telefone do sindicalizado é invalido", "Atenção", JOptionPane.ERROR_MESSAGE);
                CELULAR.setText("(  ) 9     -     ");
                CELULAR.requestFocus();
            }
        } else if (!"".equals(RESERVISTA.getText()) && erro == 0) {
            String RESER = si.validarReservista(RESERVISTA.getText());
            if ("".equals(RESER)) {
                erro = 1;
                JOptionPane.showMessageDialog(null, "O número da reservista do sindicalizado é invalido.", "Atenção", JOptionPane.ERROR_MESSAGE);
                RESERVISTA.setText("");
                RESERVISTA.requestFocus();
            }
        } else if (!"              ".equals(TITULO_ELEITO.getText()) && erro == 0) {
            String titu = si.validar_Titulo_Eleitor(TITULO_ELEITO.getText());
            if ("".equals(titu)) {
                erro = 1;
                JOptionPane.showMessageDialog(null, "O titulo de eleitor do sindicalizado é invalido.", "Atenção", JOptionPane.ERROR_MESSAGE);
                TITULO_ELEITO.setText("              ");
                TITULO_ELEITO.requestFocus();
            }
        } else if (!"   ".equals(ZONA.getText()) && erro == 0) {
            String zona = si.validar_zona(ZONA.getText());
            if ("".equals(zona)) {
                erro = 1;
                JOptionPane.showMessageDialog(null, "A zona do titulo de eleitor do sindicalizado é invalida.", "Atenção", JOptionPane.ERROR_MESSAGE);
                ZONA.setText("   ");
                ZONA.requestFocus();
            }
        } else if (!"    ".equals(SECAO.getText()) && erro == 0) {
            String secao = si.validar_secao(SECAO.getText());
            if ("".equals(secao)) {
                erro = 1;
                JOptionPane.showMessageDialog(null, "A seção do titulo de eleitor do sindicalizado é invalida.", "Atenção", JOptionPane.ERROR_MESSAGE);
                SECAO.setText("   ");
                SECAO.requestFocus();
            }
        }

        if (erro == 0) {
            cont = true;
        } else if (erro == 1) {
            cont = false;
        }

        return cont;
    }

    public boolean validar_obrigatorios_rurais() {
        erro = 0;
        if ("".equals(NOMEFAZENDA.getText()) && erro == 0) {
            JOptionPane.showMessageDialog(null, "Informe o nome da propriedade rural");
            NOMEFAZENDA.requestFocus();
            erro = 1;
        } else if ("".equals(LOGRADOURO.getText()) && erro == 0) {
            JOptionPane.showMessageDialog(null, "Informe o logradouro da propriedade rural");
            LOGRADOURO.requestFocus();
            erro = 1;
        } else if ("".equals(MUNICEDE.getText()) && erro == 0) {
            JOptionPane.showMessageDialog(null, "Informe o municipio cede da propriedade rural");
            MUNICEDE.requestFocus();
            erro = 1;
        } else if ("".equals(AREAFAZENDA.getText()) && erro == 0) {
            JOptionPane.showMessageDialog(null, "Informe a area da propriedade rural");
            AREAFAZENDA.requestFocus();
            erro = 1;
        } else if ("".equals(TEMPOCOMPRA.getText()) && erro == 0) {
            JOptionPane.showMessageDialog(null, "Informe o tempo de compra da propriedade rural");
            TEMPOCOMPRA.requestFocus();
            erro = 1;
        } else if ("   .   .   .   - ".equals(CODINCRA.getText()) && erro == 0) {
            JOptionPane.showMessageDialog(null, "Informe o código no Incra da propriedade rural");
            CODINCRA.requestFocus();
        } else if (!"   .   .   .   - ".equals(CODINCRA.getText()) && erro == 0) {
            String codI = si.validaCodIncra(CODINCRA.getText());
            if ("".equals(codI)) {
                erro = 1;
                JOptionPane.showMessageDialog(null, "O código no INCRA da propriedade rural informado é invalido.", "Atenção", JOptionPane.ERROR_MESSAGE);
                CODINCRA.setValue("");
                CODINCRA.requestFocus();
            } else {
                String i;
                if ("altera propri".equals(status)) {
                    i = si.verificar_INCRA(codI, id);
                } else {
                    i = si.verificar_INCRA(codI, 0);
                }
                if ("tem dono".equals(i)) {
                    erro = 1;
                    JOptionPane.showMessageDialog(null, "O código no INCRA da propriedade rural informado já esta cadastrado", "Atenção Código no INCRA invalido", JOptionPane.ERROR_MESSAGE);
                    CODINCRA.setText("");
                    CODINCRA.requestFocus();
                }
            }
        }

        if (" .   .   - ".equals(Numero_NIRF.getText()) && erro == 0) {
            erro = 1;
            JOptionPane.showMessageDialog(null, "Informe o número da propriedade rural no   NIRF", "Atenção", JOptionPane.ERROR_MESSAGE);
            Numero_NIRF.setValue("");
            Numero_NIRF.requestFocus();
        } else if (!" .   .   - ".equals(Numero_NIRF.getText()) && erro == 0) {
            String nirf = si.validarNIRF(Numero_NIRF.getText());
            if ("".equals(nirf)) {
                erro = 1;
                JOptionPane.showMessageDialog(null, "O número do NIRF do sindicalizado é invalido.", "Atenção", JOptionPane.ERROR_MESSAGE);
                Numero_NIRF.setText(" .   .   - ");
                Numero_NIRF.requestFocus();
            } else {
                String i;
                if ("altera propri".equals(status)) {
                    i = si.verificar_NIRF(nirf, id);
                } else {
                    i = si.verificar_NIRF(nirf, 0);
                }
                if ("tem dono".equals(i)) {
                    erro = 1;
                    JOptionPane.showMessageDialog(null, "O número do NIRF informado já esta cadastrado", "Atenção RG invalido", JOptionPane.ERROR_MESSAGE);
                    Numero_NIRF.setText("");
                    Numero_NIRF.requestFocus();
                }
            }
        }

        if (erro == 0) {
            cont = true;
        } else if (erro == 1) {
            cont = false;
        }

        return cont;
    }

    public void LISTAR_TABELA(ArrayList<Dados_Rurais> DADOS_RU) {
        if ("cadastrar sind".equals(status)) {
            ID_TABELA++;
        }
        DefaultTableModel dtma = (DefaultTableModel) TABELA_PROPRIEDADE_RURAL.getModel();
        dtma.setNumRows(0);

        TABELA_PROPRIEDADE_RURAL.getColumnModel().getColumn(2).setPreferredWidth(110);

        TABELA_PROPRIEDADE_RURAL.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        DADOS_RU.forEach((dr) -> {
            if ("cadastrar sind".equals(status)) {               
                dr.setId(ID_TABELA);
            } else if ("altera propri".equals(status)) {
                ID_TABELA++;
            }

            dtma.addRow(new Object[]{
                dr.getId(),
                dr.getNomeFazenda(),
                dr.getAreaPropri(),
                dr.getMuniciSede(),
                dr.getTempoCompra(),
                dr.getLogradouro(),
                dr.getNIRF(),
                dr.getCodINCRA(),
                dr.getResidenciaAtual(),
                dr.getOutrasA()
            });
        });
    }

    public Dados_Pessoais preencher_objeto_Pessoal() {
        dadosp.setNome(NOME.getText());
        String dtn = df.format(NASCIMENTO.getDate());
        dadosp.setDataNasci(Util.STRING_DATE(dtn));
        dadosp.setCelular(CELULAR.getText());
        dadosp.setNascionalidade(NASCIONALIDADE.getText());
        dadosp.setEstadoCivil(String.valueOf(ESTADOCIVI.getSelectedItem()));
        dadosp.setCpf(CPF.getText());
        dadosp.setRg(RG.getText());
        String dte = df.format(DATAEXPE.getDate());
        dadosp.setDataExpedicao(Util.STRING_DATE(dte));
        dadosp.setTituloEleito(TITULO_ELEITO.getText());
        if (!"   ".equals(ZONA.getText())) {
            dadosp.setZona(Integer.parseInt(ZONA.getText()));
        }
        if (!"    ".equals(SECAO.getText())) {
            dadosp.setSecao(Integer.parseInt(SECAO.getText()));
        }
        dadosp.setReservista(RESERVISTA.getText());
        dadosp.setCategoria(CATEGORIA.getText());
        dadosp.setPai(PAI.getText());
        dadosp.setMae(MAE.getText());
        dadosp.setExcluido(0);

        return dadosp;
    }

    public Dados_Rurais preencher_objeto_Rural() {
        pr = new Dados_Rurais();
        pr.setNomeFazenda(NOMEFAZENDA.getText());
        pr.setLogradouro(LOGRADOURO.getText());
        pr.setMuniciSede(MUNICEDE.getText());
        pr.setCodINCRA(CODINCRA.getText());
        pr.setNIRF(Numero_NIRF.getText());
        pr.setAreaPropri(AREAFAZENDA.getText());
        pr.setTempoCompra(TEMPOCOMPRA.getText());
        pr.setOutrasA(OUTRASATIVI.getText());
        pr.setResidenciaAtual(RESIDEN_ATUAL.getText());
        pr.setExcluido(0);
        if ("altera propri".equals(status)) {
            pr.setId(id);
        }

        return pr;
    }

    public void limparTabela(int nu) {
        nu += 1;
        for (int e = 0; e < nu; e++) {
            DefaultTableModel dtma = (DefaultTableModel) TABELA_PROPRIEDADE_RURAL.getModel();
            dtma.removeRow(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AREAFAZENDA;
    private javax.swing.JLabel BOTAO_ALTERAR_;
    private javax.swing.JLabel BOTAO_AVANCAR_;
    private javax.swing.JButton BOTAO_CADASTRAR_;
    private javax.swing.JLabel BOTAO_REFAZER_;
    private javax.swing.JLabel BOTAO_SALVAR_;
    private javax.swing.JLabel BOTAO_VOLTAR_;
    private javax.swing.JLabel CANCELAR;
    private javax.swing.JTextField CATEGORIA;
    private javax.swing.JFormattedTextField CELULAR;
    private javax.swing.JFormattedTextField CODINCRA;
    private javax.swing.JFormattedTextField CPF;
    private javax.swing.JPanel DADOS_PESSOAIS_SIND;
    private javax.swing.JPanel DADOS_RURAIS_SIND;
    private com.toedter.calendar.JDateChooser DATAEXPE;
    private javax.swing.JComboBox<String> ESTADOCIVI;
    private javax.swing.JTabbedPane FORM_GUIAS;
    private javax.swing.JTextField LOGRADOURO;
    private javax.swing.JTextField MAE;
    private javax.swing.JTextField MUNICEDE;
    private com.toedter.calendar.JDateChooser NASCIMENTO;
    private javax.swing.JTextField NASCIONALIDADE;
    private javax.swing.JTextField NOME;
    private javax.swing.JTextField NOMEFAZENDA;
    private javax.swing.JFormattedTextField Numero_NIRF;
    private javax.swing.JTextPane OUTRASATIVI;
    private javax.swing.JTextField PAI;
    private javax.swing.JPanel PESQUISAR_SIND;
    private javax.swing.JFormattedTextField RESERVISTA;
    private javax.swing.JTextField RESIDEN_ATUAL;
    private javax.swing.JFormattedTextField RG;
    private javax.swing.JFormattedTextField SECAO;
    private javax.swing.JTable TABELA_PROPRIEDADE_RURAL;
    private javax.swing.JTextField TEMPOCOMPRA;
    private javax.swing.JFormattedTextField TITULO_ELEITO;
    private javax.swing.JTextField TOTAL_FAZ;
    private javax.swing.JLabel TOTAO_REFAZER;
    private javax.swing.JFormattedTextField ZONA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
