/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Fundo_tela_Inicial;
import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author helde
 */
public class Interface extends javax.swing.JFrame {

    Fundo_tela_Inicial tela;
    
    public Interface() {
        initComponents();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); // não reconhece o clique no botao de fechar a janela toda
        
        setLayout(new GridLayout());
        tela = new Fundo_tela_Inicial("src/Imagens/SIRA.png");
        getContentPane().add(tela);
        
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void bloquiarMenus(boolean adm){
        if(adm == true){
            MENU_PESQUISAR.setVisible(false);
        }else{
            MENU_SALVAR.setVisible(false);
            MENU_PE.setVisible(false);
            MENU_EXCLUIR.setVisible(false);
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MENU_SALVAR = new javax.swing.JMenu();
        MENU_CAD_USU = new javax.swing.JMenuItem();
        MENU_PE = new javax.swing.JMenu();
        MENU_PESQUISAR = new javax.swing.JMenu();
        MENU_EXCLUIR = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        Menu_SAIR = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MENU_SALVAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SALVAR 2.png"))); // NOI18N
        MENU_SALVAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MENU_SALVARMouseEntered(evt);
            }
        });

        MENU_CAD_USU.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        MENU_CAD_USU.setText("Usuário");
        MENU_CAD_USU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MENU_CAD_USUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MENU_CAD_USUMouseEntered(evt);
            }
        });
        MENU_CAD_USU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_CAD_USUActionPerformed(evt);
            }
        });
        MENU_SALVAR.add(MENU_CAD_USU);

        jMenuBar1.add(MENU_SALVAR);

        MENU_PE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar_editar.png"))); // NOI18N
        jMenuBar1.add(MENU_PE);

        MENU_PESQUISAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PESQUISAR (2).png"))); // NOI18N
        jMenuBar1.add(MENU_PESQUISAR);

        MENU_EXCLUIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ESCLUIR 2.png"))); // NOI18N
        jMenuBar1.add(MENU_EXCLUIR);

        jMenu5.setEnabled(false);
        jMenu5.setMaximumSize(new java.awt.Dimension(1000, 32767));
        jMenu5.setPreferredSize(new java.awt.Dimension(700, 19));
        jMenuBar1.add(jMenu5);

        Menu_SAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SAIR 2.png"))); // NOI18N
        Menu_SAIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_SAIRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu_SAIRMouseEntered(evt);
            }
        });
        jMenuBar1.add(Menu_SAIR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_SAIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_SAIRMouseClicked
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja Sair Realmente?", "Sair",JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {  
                        System.exit(0);  
                    }
    }//GEN-LAST:event_Menu_SAIRMouseClicked

    private void Menu_SAIRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_SAIRMouseEntered
             Menu_SAIR.setToolTipText("Sair");
    }//GEN-LAST:event_Menu_SAIRMouseEntered

    private void MENU_CAD_USUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_CAD_USUActionPerformed
        PerfilUsu pu = new PerfilUsu();
        pu.setVisible(true);
    }//GEN-LAST:event_MENU_CAD_USUActionPerformed

    private void MENU_CAD_USUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MENU_CAD_USUMouseEntered
        MENU_CAD_USU.setToolTipText("Cadastrar usuário");
    }//GEN-LAST:event_MENU_CAD_USUMouseEntered

    private void MENU_CAD_USUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MENU_CAD_USUMouseClicked
        
    }//GEN-LAST:event_MENU_CAD_USUMouseClicked

    private void MENU_SALVARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MENU_SALVARMouseEntered
        MENU_SALVAR.setToolTipText("Cadastrar");
    }//GEN-LAST:event_MENU_SALVARMouseEntered

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MENU_CAD_USU;
    private javax.swing.JMenu MENU_EXCLUIR;
    private javax.swing.JMenu MENU_PE;
    private javax.swing.JMenu MENU_PESQUISAR;
    private javax.swing.JMenu MENU_SALVAR;
    private javax.swing.JMenu Menu_SAIR;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
